#!/usr/bin/env python3
"""
Generate a biweekly slides deck of top papers from the AI Health Literature Review.
Outputs both:
  - Markdown (for reveal.js or manual conversion)
  - PPTX (via pandoc if available)
"""
import sqlite3
import os
import subprocess
from datetime import datetime, timedelta
from pathlib import Path
import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = os.getenv('PAPERS_DB', str(PROJECT_ROOT / 'data' / 'papers.db'))
OUTPUT_DIR = PROJECT_ROOT / 'outputs' / 'slides'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def load_config():
    config_path = PROJECT_ROOT / 'config.yaml'
    with open(config_path) as f:
        return yaml.safe_load(f)

def get_top_papers(since_days=14, min_score=8.0, limit=10):
    """Fetch top papers from the last N days with score above threshold."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cutoff = (datetime.now() - timedelta(days=since_days)).isoformat()
    query = """
        SELECT paper_id, title, authors, venue, published_date, score, summary, critique, gaps, url, doi
        FROM papers
        WHERE processing_status = 'presented'
          AND score >= ?
          AND published_date >= ?
        ORDER BY score DESC, published_date DESC
        LIMIT ?
    """
    cursor.execute(query, (min_score, cutoff, limit))
    rows = [dict(row) for row in cursor.fetchall()]
    conn.close()
    return rows

def render_slides_markdown(papers):
    today = datetime.now().strftime('%Y-%m-%d')
    lines = [
        f"# AI Health Lit Review — Top Picks ({today})",
        "",
        "---",
        "",
        "## 📊 Summary",
        "",
        f"- **Plage de dates** : 14 derniers jours",
        f"- **Nombre de papiers présentés** : {len(papers)}",
        f"- **Score minimum** : 8.0",
        "",
        "---",
        "",
        "## 🏆 Highlights",
        ""
    ]
    for i, p in enumerate(papers, 1):
        lines.extend([
            f"### {i}. {p['title']}",
            "",
            f"**Score** : {p['score']}/10  **Venue** : {p.get('venue','N/A')}",
            "",
            "**Summarized insight** :",
            f"> {p.get('summary','N/A')}",
            "",
            "**Critical note** :",
            f"> {p.get('critique','N/A')}",
            "",
            "**Key gaps** :",
            f"> {p.get('gaps','N/A')}",
            "",
            f"[Link]({p.get('url','#')})",
            "",
            "---",
            ""
        ])
    lines.append("## 🔭 Take‑aways")
    lines.append("")
    lines.append("- This deck captures the highest‑scoring, clinically adjacent AI papers from the last two weeks.")
    lines.append("- Use it as a quick briefing or a starting point for deeper discussion.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by AI Health Lit Review on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    return "\n".join(lines)

def convert_to_pptx(md_path: Path, pptx_path: Path):
    """Convert markdown to PPTX using pandoc."""
    try:
        subprocess.run([
            'pandoc', str(md_path),
            '-t', 'pptx',
            '-o', str(pptx_path)
        ], check=True, capture_output=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"Pandoc conversion failed: {e}")
        return False

def main():
    cfg = load_config()
    if not os.path.exists(DB_PATH):
        print(f"Database not found at {DB_PATH}")
        return
    papers = get_top_papers(since_days=14, min_score=8.0, limit=10)
    if not papers:
        print("No papers matched criteria.")
        return
    md = render_slides_markdown(papers)
    date_str = datetime.now().strftime('%Y-%m-%d')
    md_path = OUTPUT_DIR / f"slides_{date_str}.md"
    pptx_path = OUTPUT_DIR / f"slides_{date_str}.pptx"
    md_path.write_text(md)
    print(f"Slides written to {md_path}")
    # Attempt PPTX conversion
    ok = convert_to_pptx(md_path, pptx_path)
    if ok:
        print(f"Converted to {pptx_path}")
    else:
        print("PPTX not generated (pandoc missing or failed). You can convert manually:")
        print(f"  pandoc {md_path} -t pptx -o {pptx_path}")

if __name__ == '__main__':
    main()
